# Information: https://clover.coex.tech/programming

import rospy
from clover import srv
from std_srvs.srv import Trigger
import cv2
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
from clover import long_callback

bridge = CvBridge()
@long_callback
def image_callback(msg):
    imgg = bridge.imgmsg_to_cv2(msg, 'bgr8')

    # convert to HSV to work with color hue
    img = cv2.cvtColor(imgg, cv2.COLOR_BGR2HSV)
    r = 0
    g = 0
    b = 0
    i = 0
    for y in range(len(img)):
        for x in range(len(img[y])):
            u = img[y][x].tolist()
            r = r + u[1]
            b = b + u[0]
            g = g + u[2]
            i = i + 1
    r = r // i
    b = b // i
    g = g // i
    print('\r',end=f'{r},{g},{b}')

rospy.init_node('flight')

get_telemetry = rospy.ServiceProxy('get_telemetry', srv.GetTelemetry)
navigate = rospy.ServiceProxy('navigate', srv.Navigate)
set_position = rospy.ServiceProxy('set_position', srv.SetPosition)
set_velocity = rospy.ServiceProxy('set_velocity', srv.SetVelocity)
set_attitude = rospy.ServiceProxy('set_attitude', srv.SetAttitude)
set_rates = rospy.ServiceProxy('set_rates', srv.SetRates)
land = rospy.ServiceProxy('land', Trigger)


print('Take off and hover 1 m above the ground')
navigate(x=0, y=0, z=1.7, frame_id='body', auto_arm=True)

# Wait for 5 seconds
rospy.sleep(5)

y = -0.94
q = 0.94
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=q, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=q, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=q, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=q, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=q, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=q, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=q, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=q, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=q, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=q, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=y, y=0, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)










navigate(x=0, y=y, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=y, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=y, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=y, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=y, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=y, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=y, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=y, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=y, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)
navigate(x=0, y=y, z=0, frame_id='body')
rospy.sleep(5)
rospy.Subscriber('main_camera/image_raw', Image, image_callback, queue_size=1)





print('Perform landing')
land()
